version: '3.7'

services:
  nginx:
    build: nginx
    depends_on:
      - api
      - frontend
    ports:
      - "127.0.0.1:${PORT_NGINX:-80}:80"
    volumes:
      - ./nginx/svgs:/svgs

  frontend:
    container_name: frontend
    build: frontend
    command: yarn serve
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/public:/project/public
    networks:
      - nginx-network
    ports:
      - "127.0.0.1:${PORT_FRONTEND:-81}:81"

  neo4j:
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/var/lib/neo4j/import
    ports:
      - "127.0.0.1:${PORT_NEO4J_1:-7474}:7474"
      - "127.0.0.1:${PORT_NEO4J_2:-7687}:7687"

  api:
    environment:
      - NODE_ENV=develop
    volumes:
      - ./api/src:/project/src
      - ./api/svg:/project/svg
      - ./api/repository:/project/repository
      - ./api/public:/project/public
    command: yarn develop

  ftp:
    environment:
      - FTP_IP=127.0.0.1
      - FLAGS=-Y 0 -d -d
